Fixed SOIC fn
tscircuit/footprinter pull request #22
Opened 2024-08-25 21:13 UTC by anas-sarkez

Me and @ShiboSoftwareDev  found a bug in the SOIC implementation where pin width is subtracted from the pitch which affected the gap between the pins and the silkscreen, The bug was complicated to figure out and I think it should be fixed now.

2024-08-25 21:18 UTC, seveibar commented on src/fn/soic.ts
> +      v.p += v.pw
nice

2024-08-25 21:20 UTC, seveibar requested changes
i think modifying user parameters could be confusing, we should preserve the user-specified pitch and fix an error in the drawing function if there is one

2024-08-25 21:20 UTC, seveibar commented on src/fn/soic.ts
> +      v.p += v.pw
hmm looking into this a bit, I think that we don't want to modify the pitch given by the user. We want to modify or fix the drawing function (if it's incorrect)

![image](https://github.com/user-attachments/assets/42782bb3-18fe-4bce-b188-feb8e29cce69)

2024-08-25 21:23 UTC, anas-sarkez commented
**I think I can do that**

2024-08-26 12:50 UTC, anas-sarkez commented
<img width="691" alt="Screenshot 2024-08-26 at 2 44 38 PM" src="https://github.com/user-attachments/assets/befdcc76-11e1-42e9-9789-bceba98e9a34">
We fixed a bug that doesn't exist, it turned out it was behaving like it should. We just got confused by this test which doesn't make sense.

2024-08-26 12:50 UTC, closed without merging