update footprinter.ts and slop1.test.ts for better error message
tscircuit/footprinter pull request #59
Opened 2024-10-10 17:42 UTC by ChiragAgg5k

<img width="566" alt="Screenshot 2024-10-10 at 11 12 45 PM" src="https://github.com/user-attachments/assets/fbe7ba79-a53a-4e11-b390-ad77b50556ac">

2024-10-10 23:27 UTC, seveibar requested changes

2024-10-10 23:27 UTC, seveibar commented on tests/slop/slop1.test.ts
> +    })
why did you add this to a slop test? can you move it to a different test file? Also you should request me for review to  get a review faster

2024-10-11 02:54 UTC, ChiragAgg5k commented
@seveibar can you tell me which file should i add it to? thanks

2024-10-11 02:55 UTC, seveibar commented
@ChiragAgg5k a new file, you could call it fp-string-error.test.ts

2024-10-11 02:59 UTC, ChiragAgg5k commented
@seveibar can u check now?

2024-10-11 03:02 UTC, seveibar commented on tests/fp-string-error.test.ts
> +      expect(error.message).toContain("Function not found for footprinter")
You have to test that “invalidFunction” appears in the error output, that is the key part of the implementation that you added, so you should test it

2024-10-11 03:03 UTC, seveibar commented on tests/slop/slop1.test.ts
> +import { getTestFixture } from "../fixtures" // Adjust path based on your structure
Revert the changes to this file (eg with git chrckout origin/main — path/to/file.ts), also in this file and the other file remove the ai generated comments

2024-10-11 03:04 UTC, seveibar requested changes

2024-10-11 03:04 UTC, seveibar commented on tests/fp-string-error.test.ts
> +      expect(error.message).toContain("Function not found for footprinter")
Better to just test an exact match for the whole message this test is hard to read. Just tell ne as the reviewer the full message with a toEqual assertion

2024-10-11 03:12 UTC, ChiragAgg5k commented
I couldn't find a helper function that converts the input function string to its equivalent form. For eg. "invalidFunction" to "invalid". Should I use regex in the testfile itself?

2024-10-11 04:23 UTC, ChiragAgg5k commented
<img width="832" alt="Screenshot 2024-10-11 at 9 53 08 AM" src="https://github.com/user-attachments/assets/23c467f4-0888-48b1-a344-aa49a7a754ff">

@seveibar

2024-10-11 04:27 UTC, seveibar commented
@ChiragAgg5k i dont understand. The issue is the user types something like fp.string(“trianglularsmt4”) and we want to tell them that either “triangularsmt4” is not a function or (also acceptable) “triangularsmt” is not a function. Whatever error message it produces should be deterministic

2024-10-11 04:28 UTC, ChiragAgg5k commented
well i am confused if user wrong "triangularSmt4", then the target.fn returns "triangular", which would not match with user's original input

2024-10-11 04:37 UTC, ChiragAgg5k commented
@seveibar do check now

2024-10-11 04:56 UTC, seveibar requested changes
I have no idea what is going on with your test. Just run fp.string("traingularsmt4") and expect an error. No loops or other complexity. Why do you need a test fixture.

Also fix typos

2024-10-11 04:57 UTC, seveibar requested changes

2024-10-11 04:57 UTC, seveibar commented on tests/fp-string-error.test.ts
> +        `Function not found for footprinter "${invalidFootprintParts[0]?.fn}". Specify a valid function like .dip, .lr, .p, etc.`,
This line. It should be a fixed error. No interpolation allowed

2024-10-11 05:07 UTC, ChiragAgg5k commented
@seveibar sorry my bad. now i am just running the invalid case and expecting error. looks good?

2024-10-11 13:31 UTC, seveibar commented on tests/fp-string-error.test.ts
> +    const { fp } = await getTestFixture("slop1")
```suggestion
    const { fp } = await getTestFixture("fp string error with invalid fn")
```

2024-10-11 13:31 UTC, seveibar commented on tests/fp-string-error.test.ts
> +      expect.fail("Expected an exrror to be thrown, but no error was thrown")
```suggestion
      expect.fail("Expected an error to be thrown, but no error was thrown")
```

2024-10-11 13:33 UTC, seveibar commented
You’re still not testing for the error message. As the reviewer i need to see the error message to confirm that it is properly erroring.

2024-10-11 13:54 UTC, closed without merging